app/models/base.py
from app.extensions import db

class Base(db.Model):
    __abstract__ = True

    id = db.Column(db.Integer, primary_key=True)

app/routes/home.py
from flask import Blueprint, render_template, session

home_bp = Blueprint('home', __name__)


@home_bp.route('/')
@home_bp.route('/home')
def home() -> str:
    return render_template('main.html', session=session)

app/routes/render/auth.py
from flask import Blueprint, request, session, redirect, url_for, Response, flash
from app.models import User

auth_bp = Blueprint('auth', __name__, url_prefix='/auth') # blueprint як підпрограма, яка потім в основному файлі підключається до основного застосунку


@auth_bp.route('/login', methods=['POST'])
def login() -> Response:
    identifier = request.form['identifier'].strip()
    password = request.form['password']

    existing_user = User.query.filter((User.username==identifier) | (User.email==identifier)).first()

    if existing_user:
        if not existing_user.check_password(password):
            flash('Неправильний пароль', 'error') # дозволяє зберегти одноразове повідомлення в сесії користувача, зберігається в session['_flashes'], існує до наступного http запиту (get_flashed_messages на вбюшці)
            return redirect(url_for('auth.login'))
        session['user'] = existing_user.username
        session['id'] = existing_user.id
    else:
        flash('Користувача не знайдено', 'danger')
        return redirect(url_for('auth.login'))
    return redirect(url_for('account_view.homepage'))


@auth_bp.route('/logout')
def logout() -> Response:
    if session.get('user'):
        session.pop('user')
        session.pop('id')
        return redirect(url_for('home.home'))
    else:
        return redirect(url_for('auth.login'))

app/routes/workouts.py
from flask import Blueprint, request, render_template, session, url_for, redirect, Response
from app.models import User, Workout, Exercise, Set, Equipment
from app.extensions import db
from datetime import datetime
from app.decorators import login_required, owner_required

workouts_bp = Blueprint('workouts', __name__, url_prefix='/workouts')


@workouts_bp.route('/view/<int:workout_id>')
@login_required
@owner_required(Workout, param='workout_id')
def workouts_view(workout) -> str:
    return render_template('workout_details.html', workout=workout)


@workouts_bp.route('/createWorkout', methods=['GET', 'POST'])
@login_required
def create_workout() -> str:
    if request.method == 'GET':
        return render_template('create_workout.html')

    name = request.form['name']
    date = request.form['date']
    user = User.query.filter_by(username=session['user']).first()

    if not name and not date:
        return render_template('create_workout.html', error='Потрібно заповнити усі поля')

    if not user:
        return render_template('error.html', error='Користувач незареєстрований')

    parsed_date = datetime.strptime(date, '%Y-%m-%d')

    try:
        db.session.add(Workout(name, parsed_date, user))
        db.session.commit()
        return render_template('homepage.html', workouts=user.workouts)
    except Exception as e:
        print(e)
        return render_template('error.html', error=e)


@workouts_bp.route('/addExercise/<int:workout_id>', methods=['POST', 'GET'])
@login_required
@owner_required(Workout, param='workout_id')
def add_exercise(workout) -> str | Response:
    if request.method == 'GET':
        return render_template('add_exercise.html', workout_id=workout.id)

    user = User.query.filter_by(username=session['user']).first()
    if not user:
        return render_template('error.html', error='Ви не ввійшли')

    name = request.form['name']
    equipment = request.form['equipment']

    if not name:
        return render_template('add_exercise.html', error='Введіть назву вправи')

    try:
        exercise = Exercise(name, workout)
        db.session.add(exercise)
        if equipment:
            db.session.add(Equipment(equipment, exercise))
        db.session.commit()
        return redirect(url_for('workouts.workouts_view', workout_id=workout.id))
    except Exception as e:
        print(e)
        return render_template('error.html', error=e)


@workouts_bp.route('/addEquipment/<int:exercise_id>', methods=['POST'])
@login_required
@owner_required(Exercise, param='exercise_id')
def add_equipment(exercise) -> str:
    name = request.form['name']
    if not name:
        return render_template('error.html', error='Введіть назву устаткування')

    try:
        db.session.add(Equipment(name, exercise=exercise))
        db.session.commit()
        return render_template('workout_details.html', workout=exercise.workout)
    except Exception as e:
        print(e)
        return render_template('error.html', error=e)


@workouts_bp.route('/addSets/<int:equipment_id>', methods=['POST'])
@login_required
@owner_required(Equipment, param='equipment_id')
def add_sets(equipment) -> str:

    count = int(request.form['count'])
    weight = float(request.form['weight'])
    rest_time = datetime.strptime(request.form['rest_time'], '%H:%M:%S')

    if not count:
        return render_template('error.html', error='Потрібно ввести кількість повторів')

    if not weight:
        return render_template('error.html', error='Потрібно ввести вагу під час підходу')

    try:
        db.session.add(Set(count, weight, rest_time, equipment))
        db.session.commit()
        return render_template('workout_details.html', workout=equipment.exercise.workout)
    except Exception as e:
        print(e)
        return render_template('error.html', error=e)


@workouts_bp.route('/filter')
@login_required
def filter_workouts() -> str:
    """
    Тут треба зрозуміти, що можна отримати query і далі його за потреби фільтрувати, а не писати все в один рядок
    також потрібно використовувати query параметри, так як це зручно, наприклад для фільтрування
    """
    user_id = session['id']
    name = request.args.get('name') # query параметри, передаються ось так: /filter?name=Push&date=2025-08-30, якщо такого параметру немає, то повертає None
    name = name.strip() if name else None
    date_str = request.args.get('date') # request.args зберігає query параметри, які ми передаємо через браузерну строку

    query = Workout.query.filter_by(user_id=user_id)

    if name:
        query = query.filter(Workout.name.ilike(f"%{name}%"))

    if date_str:
        try:
            date = datetime.strptime(date_str, '%Y-%m-%d').date()
            query = query.filter(db.func.date(Workout.date) == date)
        except ValueError as e:
            print(e)
            return render_template('error.html', error='Невірний формат дати. YYYY-MM-DD')

    workouts = query.order_by(Workout.date.desc()).all()
    return render_template('homepage.html', workouts=workouts)

app/templates/add_exercise.html
{% extends "base.html" %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='addExerciseStyles.css') }}">
<div class="container">
    <h2>Додати вправу</h2>

    {% if error %}
        <div style="color:red;">{{ error }}</div>
    {% endif %}

    <form method="POST" action="{{ url_for('workouts.add_exercise', workout_id=workout_id) }}" class="exercise-form">
        <div>
            <label for="name">Назва вправи:</label>
            <input type="text" id="name" name="name" required>
        </div>

        <div>
            <label for="equipment">Тренажери / обладнання:</label>
            <input type="text" id="equipment" name="equipment">
        </div>

        <div>
            <button type="submit">Додати</button>
        </div>
    </form>
</div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Мій тренувальний застосунок{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>

<header>
    <nav>
        <div class="logo">🏋️ МійGYM</div>
        <ul class="nav-links">
            <li><a href="{{ url_for('home.home') }}">Головна</a></li>
            {% if 'user' in session %}
                <li><a href="{{ url_for('account_view.homepage') }}">Мої тренування</a></li>
                <li><a href="">Профіль</a></li>
                <li><a href="{{ url_for('auth.logout') }}">Вийти</a></li>
            {% else %}
                <li><a href="{{ url_for('auth.login') }}">Увійти</a></li>
            {% endif %}
        </ul>
    </nav>
</header>

    <main>
        {% block content %}{% endblock %}
    </main>

    <footer>
        <p>&copy; {{ current_year }} Мій тренувальний застосунок</p>
    </footer>
</body>
</html>

app/templates/create_workout.html
{% extends "base.html" %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='createWorkout.css') }}">
<div class="create-container">
    <h1>Створити тренування</h1>

    {% if error %}
        <div class="error-message">
            {{ error }}
        </div>
    {% endif %}

    <form method="POST" action="{{ url_for('workouts.create_workout') }}" class="workout-form">
        <label for="name">Назва тренування:</label>
        <input type="text" id="name" name="name" required>

        <label for="date">Дата:</label>
        <input type="date" id="date" name="date" required>

        <button type="submit">Створити</button>
    </form>
</div>
{% endblock %}

app/templates/error.html
{% extends "base.html" %}

{% block title %}Помилка{% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='errorStyles.css')}}">
<div class="error-container">
    <h2>Виникла помилка</h2>
    <p>{{ error }}</p>
    <a href="{{ url_for('home.home') }}">На головну</a>
</div>
{% endblock %}

app/templates/homepage.html
{% extends "base.html" %}

{% block title %}Мій кабінет{% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='homepageStyles.css') }}">

<div class="account-container">
    <h2>Мої тренування</h2>

    <a class="add-button" href="{{ url_for('workouts_view.create_workout_view') }}">
        ➕ Додати тренування
    </a>
        {% if workouts %}
            <ul class="workout-list">
                {% for workout in workouts %}
                    <li class="workout-item">
                        <div class="workout-info">
                            <strong>{{ workout.name }}</strong>
                            <span class="workout-date">{{ workout.date.strftime("%d.%m.%Y %H:%M") }}</span>
                        </div>
                        <a class="view-link" href="{{ url_for('workouts_view.workouts_view', workout_id=workout.id) }}">
                            🔗 Відкрити
                        </a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p class="no-workouts">У вас ще немає тренувань.</p>
        {% endif %}
</div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block title %}Вхід{% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='loginStyles.css') }}">

<div class="form-container">
    <h2>Вхід</h2>

    {% with errors = get_flashed_messages(with_categories=true) %} <! отримує повідомлення з session['_flashes] як списки або (categories, message) якщо присутня категорія другим параметром в flash() на сервері -->
        {% for category, message in messages %}
            {% if category == 'error' %}
                <div class="error-message">{{ message }}</div>
            {% endif %}
        {% endfor %}
    {% endwith %}

    <form method="POST" action="{{ url_for('auth.login') }}">
        <label for="identifier">Логін або Email</label>
        <input type="text" id="identifier" name="identifier" required>

        <label for="password">Пароль</label>
        <input type="password" id="password" name="password" required>

        <button type="submit">Увійти</button>
    </form>
</div>
{% endblock %}

app/templates/main.html
{% extends "base.html" %}

{% block title %}Головна{% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='homeStyles.css') }}">
<div class="main-container">
    <h1>Ласкаво просимо до Workout Tracker!</h1>
    <p>
        Тут ти можеш легко відстежувати свої тренування, додавати нові вправи,
        переглядати історію підходів та повторів. Все у зручному та зрозумілому інтерфейсі.
    </p>
    <p>
        Почни з реєстрації або увійди в свій акаунт, щоб створити перше тренування.
    </p>
    <h2><a href="{{ url_for('account.register') }}">Реєстрація</a></h2>
</div>

{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block title %}Реєстрація{% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='loginStyles.css') }}">

<div class="form-container">
    <h2>Реєстрація користувача</h2>

    {% with errors = get_flashed_messages(with_categories=true) %}
        {% for category, error in errors %}
            {% if category == 'error' %}
                <div class="error-message">{{ error }}</div>
            {% endif %}
        {% endfor %}
    {% endwith %}

    <form method="POST" action="{{ url_for('account.register') }}">
        <label for="username">Логін</label>
        <input type="text" id="username" name="username" required>

        <label for="email">Email</label>
        <input type="email" id="email" name="email" required>

        <label for="password">Пароль</label>
        <input type="password" id="password" name="password" required>

        <button type="submit">Зареєструватися</button>
    </form>
</div>
{% endblock %}

app/templates/workout_details.html
{% extends "base.html" %}

{% block title %}Тренування: {{ workout.name }}{% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='workoutDetailsStyles.css') }}">
<div class="workout-detail">
    <h2>{{ workout.name }}</h2>
    <p><strong>Дата:</strong> {{ workout.date.strftime('%d.%m.%Y') }}</p>
    <div class="mb-3">
        <a class="btn" href="{{ url_for('workouts.add_exercise', workout_id=workout.id) }}">
            ➕ Додати вправу
        </a>
    </div>

    {% if workout.exercises %}
        {% for exercise in workout.exercises %}
            <div class="exercise-block">
                <h3>Вправа: {{ exercise.name }}</h3>
                <form method="POST" action="{{ url_for('workouts.add_equipment', exercise_id=exercise.id) }}">
                    <label for="name">Назва устаткування</label>
                    <input type="text" id="name" name="name" required>
                    <button type="submit">Додати</button>
                </form>
                {% if exercise.equipments %}
                    {% for equipment in exercise.equipments %}
                        <div class="machine-block">
                            <h4>Тренажер: {{ equipment.name }}</h4>
                            <form method="POST" action="{{ url_for('workouts.add_sets', equipment_id=equipment.id) }}">
                                <label for="count">Повтори</label>
                                    <input type="text" id="count" name="count" required>
                                <label for="rest_time">Час відпочинку</label>
                                    <input type="time" id="rest_time" name="rest_time" step="1">
                                <label for="weight">Вага</label>
                                    <input type="number" id="weight" name="weight" required>
                                <button type="submit">Додати</button>
                            </form>
                            {% if equipment.sets %}
                                <ul class="sets-list">
                                    {% for s in equipment.sets %}
                                        <li>
                                            Підхід {{ loop.index }}: {{ s.count }} повторів, вага {{s.weight}}, відпочинок {{ s.rest_time.strftime('%H:%M:%S') }}
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% else %}
                                <p>Немає підходів</p>
                            {% endif %}
                        </div>
                    {% endfor %}
                {% else %}
                    <p>Устаткування не вказано</p>
                {% endif %}
            </div>
        {% endfor %}
    {% else %}
        <p>Немає вправ у цьому тренуванні</p>
    {% endif %}
</div>
{% endblock %}